# Generated by Django 5.2.7 on 2025-11-04 18:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.menu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
