# Generated by Django 5.2.7 on 2025-11-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitem_menu_alter_menu_menu_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
    ]
