# Generated by Django 5.2.7 on 2025-11-04 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_menu_data_alter_menuitem_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='data',
            new_name='categories',
        ),
    ]
