# Generated by Django 5.2.7 on 2025-11-04 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_data_menu_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='categories',
        ),
    ]
