# Generated by Django 5.2.7 on 2025-11-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_menu_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
